## 4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [4]:
import numpy as np

Array = np.zeros((2,2))
Array


array([[0., 0.],
       [0., 0.]])

2. Subtract the two array.

In [7]:
Array= np.zeros((4,2))
Array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}


In [12]:
Array = np.full((2,3),5)
Array

array([[5, 5, 5],
       [5, 5, 5]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [14]:
A= np.array ([[1,2],[3,4]])
a=np.zeros_like(A)
a

array([[0, 0],
       [0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [17]:
A = np.array([[4,5],[3,4]])
a = np.ones_like(A)
a

array([[1, 1],
       [1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [18]:
new_list=[1,2,3,4]
a=np.array(new_list)
a

array([1, 2, 3, 4])

## **Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [19]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [21]:
Array = np.arange(0,9)
Array = np.reshape(Array,(3,3))
Array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [22]:
Array = np.eye(3)
Array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [26]:
array = np.random.random(30)
array = array.mean()
array

np.float64(0.5548176599448674)

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [33]:
Array = np.random.random((10,10))

print("Minimun Value:",Array.min())
print("Maximum Value:",Array.max())
Array

Minimun Value: 0.0026890823921328355
Maximum Value: 0.9943234794814074


array([[0.41491064, 0.89942918, 0.48901089, 0.83923019, 0.99322556,
        0.52486571, 0.14638255, 0.80618646, 0.3392623 , 0.49665268],
       [0.57779762, 0.01898275, 0.47746255, 0.17506305, 0.61828645,
        0.75749516, 0.03382222, 0.8481654 , 0.06151016, 0.33658622],
       [0.33759434, 0.75643181, 0.76655274, 0.75697408, 0.38711795,
        0.37587844, 0.6502676 , 0.63146755, 0.42977636, 0.62178317],
       [0.3510532 , 0.37581571, 0.13164009, 0.55500766, 0.41897771,
        0.69110519, 0.04183089, 0.52608497, 0.91618005, 0.05910316],
       [0.92738998, 0.50576019, 0.99432348, 0.05547356, 0.35066968,
        0.17018505, 0.7793713 , 0.51238803, 0.54725585, 0.88750488],
       [0.39992432, 0.4704946 , 0.34653078, 0.16124021, 0.53307105,
        0.83142656, 0.40003097, 0.21117575, 0.86329359, 0.73144956],
       [0.04513652, 0.55758416, 0.00268908, 0.17223946, 0.51120329,
        0.14350519, 0.73693709, 0.98970324, 0.28255098, 0.54832777],
       [0.50998582, 0.41875382, 0.0140333

6. Create a zero array of size 10 and replace 5th element with 1.

In [30]:
Array = np.zeros(10)
Array[4] = 10
Array

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

7. Reverse an array arr = [1,2,0,0,4,0].

In [34]:
arr = np.array([1,2,0,0,4,0])
reverse_arr = arr[::-1]
reverse_arr

array([0, 4, 0, 0, 2, 1])

8. Create a 2d array with 1 on border and 0 inside.

In [36]:
Rows, Cols=4,4
array = np.zeros((Rows,Cols), dtype=int)
array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1
array

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [38]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## **Problem - 3: Array Operations:**
For the following arrays:

**x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);**

**v = np.array([9,10]) and w = np.array([11,12]);**

Complete all the task using numpy:

Array provided in the question:


In [40]:
x = np.array(([1,2],[3,5]))
y = np.array(([5,6],[7,8]))
v = np.array(([9,10]))
w = np.array(([11,12]))

1. Add the two array.

In [45]:
x_plus_y= x+y
v_plus_w= v+w

print("x + y :\n",x_plus_y)
print("v + w :\n",v_plus_w)

x + y :
 [[ 6  8]
 [10 13]]
v + w :
 [20 22]


2. Subtract the two array.

In [46]:
x_sub_y = x-y
v_sub_w = v-w

print("x - y :\n",x_sub_y)
print("v - w :\n",v_sub_w)

x - y :
 [[-4 -4]
 [-4 -3]]
v - w :
 [-2 -2]


3. Multiply the array with any integers of your choice.

In [49]:
x_multi_3 = x*3
v_multi_5 = v*6

print("x*3 :\n",x_multi_3)
print("v*6 :\n",v_multi_5)



x*3 :
 [[ 3  6]
 [ 9 15]]
v*6 :
 [54 60]


4. Find the square of each element of the array.

In [50]:
x_squared = x**2
y_squared = y**2
v_squared = v**2
w_squared = w**2

print("x^2 :\n",x_squared)
print("y^2 :\n",y_squared)
print("v^2 :\n",v_squared)
print("w^2 :\n",w_squared)

x^2 :
 [[ 1  4]
 [ 9 25]]
y^2 :
 [[25 36]
 [49 64]]
v^2 :
 [ 81 100]
w^2 :
 [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [51]:
x_dot_v = np.dot(x,v)
x_dot_y = np.dot(x,y)
v_dot_w = np.dot(v,w)

print("x.v :\n",x_dot_v)
print("x.y :\n",x_dot_y)
print("v.w :\n",v_dot_w)

x.v :
 [29 77]
x.y :
 [[19 22]
 [50 58]]
v.w :
 219


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [54]:
concat_x_y_rows =np.concatenate((x,y),axis=0)
print("Concatination of x and y along rows:\n",concat_x_y_rows)

v_col=v.reshape(-1,1)
w_col=w.reshape(-1,1)
concat_v_w_cols = np.concatenate((v_col,w_col),axis=1)
print("Concatination of v and w along columns:\n",concat_v_w_cols)

Concatination of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatination of v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [56]:
try:
    concat_x_V=np.concatenate((x,v), axis=0)
except Exception as e:
    print("Error:\n", e)
    print("\nExplanation: As x is 2x2 matrix but v is 1D matrix with size 2.So the dimensions do not match. Hence, concatination is not possible")

Error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: As x is 2x2 matrix but v is 1D matrix with size 2.So the dimensions do not match. Hence, concatination is not possible


# Problem - 4: Matrix Operations:
• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

In [64]:
A =np.array(([3,4],[7,8]))
B =np.array(([5,3],[2,1]))

1. Prove A.A−1 = I.

In [69]:
A_inv = np.linalg.inv(A)
A1= np.dot(A,A_inv)
A1= np.round(A1,decimals=0)
print("A * A^-1(rounded):\n", A1)

A * A^-1(rounded):
 [[1. 0.]
 [0. 1.]]


2. Prove AB ̸= BA.

In [72]:
AB =np.dot(A,B)
BA =np.dot(B,A)
print("AB =\n",AB)
print("BA =\n",BA)
print("\n AB ̸= BA, Hence proved")

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]

 AB ̸= BA, Hence proved


3. Prove (AB)T = BTAT



In [73]:
LHS= (AB).T
RHS = np.dot(B.T, A.T)
print("(AB)^T:\n", LHS)
print("B^T A^T:\n", RHS)
print("\n(AB)^T = B^T A^T, Hence proved")


(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]

(AB)^T = B^T A^T, Hence proved


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9


{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [74]:
A = np.array([[2,-3,1],
               [1,-1,2],
               [3,1,-1]])

B = np.array([-1,-3,9])

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [76]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution (x, y, z) =", X)

Solution (x, y, z) = [ 2.  1. -2.]


# 4.2 Experiment: How Fast is Numpy?

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [115]:
import time
n=1000000
L1 = list(range(n))
L2 = list(range(n))

start = time.time()
add = [L1[i] + L2[i] for i in range(n)]
end = time.time()

print(f"Time taken by python : {end - start:.5f} seconds")


Time taken by python : 0.110008 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [119]:
array1 = np.arange(n)
array2 = np.arange(n)

start = time.time()
add = array1 + array2
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 0.00009 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

In [120]:
start = time.time()
multi = [L1[i] * L2[i] for i in range(n)]
end = time.time()

elapsed = end - start
print(f"Time taken by python: {end - start:.5f} seconds")


Time taken by python: 0.00014 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [121]:
start = time.time()
multi = array1 * array2
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 0.00014 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [122]:
start = time.time()
dot = sum(L1[i] * L2[i] for i in range(n))
end = time.time()

print(f"Time taken by python: {end - start:.5f} seconds")

Time taken by python: 0.00020 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [110]:
start = time.time()
dot = np.dot(array1, array2)
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 0.00207 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

In [126]:
n = 1000

matrix1= [list(range(n)) for _ in range(n)]
matrix2= [list(range(n)) for _ in range(n)]

start = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(n))
                for j in range(n)]
               for i in range(n)]
end = time.time()

print(f"Time taken by python: {end - start:.5f} seconds")

Time taken by python: 187.57864 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [127]:
matrix1 = np.arange(n*n).reshape(n, n)
matrix2= np.arange(n*n).reshape(n, n)

start = time.time()
result_np = np.dot(matrix1, matrix2)
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 6.01896 seconds
